import { config } from 'dotenv';
config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const {
  NODE_ENV,
  PORT,
  SECRET_KEY,
  LOG_FORMAT,
  LOG_DIR,
  ORIGIN,
  EXPIRES_IN,
  MAX_ACTIVE_SESSIONS,
  EXPIRES_SESSION,
  ACCESS_SECRET_KEY,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRES_IN,
  VERIFICATION_EMAIL_LINK,
  EXPIRES_TOKEN_VERIFICATION_EMAIL,
  EMAIL,
  MAILJET_API_KEY,
  MAILJET_API_SECRET_KEY,
  NUMBER_OF_FAIL_BEFORE_LOCK,
  TIME_LOCK,
  SESSION_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  SERVEUR_URL,
  TWILIO_CLIENT_ID,
  TWILIO_CLIENT_SECRET,
  TWO_FA_SECRET_KEY,
} = process.env;
