name: Test & Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

  push-coverage:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Copy coverage to coverage-report
        run: |
          if [ -d "coverage" ]; then
            rm -rf coverage-report
            cp -r coverage coverage-report
            echo "Coverage copied."
          else
            echo "No coverage directory found, skipping."
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push coverage
        run: |
          if [ -d "coverage-report" ]; then
            git checkout -B coverage-report
            git add coverage-report
            git commit -m "Update coverage report [skip ci]" || echo "No changes to commit"
            git push origin coverage-report --force
          else
            echo "No coverage-report directory to commit, skipping."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
